module.exports = function(a) {
    return [ {
        re: /&forall;/gi,
        val: "∀"
    }, {
        re: /&part;/gi,
        val: "∂"
    }, {
        re: /&exists;/gi,
        val: "∃"
    }, {
        re: /&empty;/gi,
        val: "∅"
    }, {
        re: /&nabla;/gi,
        val: "∇"
    }, {
        re: /&isin;/gi,
        val: "∈"
    }, {
        re: /&notin;/gi,
        val: "∉"
    }, {
        re: /&ni;/gi,
        val: "∋"
    }, {
        re: /&prod;/gi,
        val: "∏"
    }, {
        re: /&sum;/gi,
        val: "∑"
    }, {
        re: /&minus;/gi,
        val: "−"
    }, {
        re: /&lowast;/gi,
        val: "∗"
    }, {
        re: /&radic;/gi,
        val: "√"
    }, {
        re: /&prop;/gi,
        val: "∝"
    }, {
        re: /&infin;/gi,
        val: "∞"
    }, {
        re: /&ang;/gi,
        val: "∠"
    }, {
        re: /&and;/gi,
        val: "∧"
    }, {
        re: /&or;/gi,
        val: "∨"
    }, {
        re: /&cap;/gi,
        val: "∩"
    }, {
        re: /&cap;/gi,
        val: "∪"
    }, {
        re: /&int;/gi,
        val: "∫"
    }, {
        re: /&there4;/gi,
        val: "∴"
    }, {
        re: /&sim;/gi,
        val: "∼"
    }, {
        re: /&cong;/gi,
        val: "≅"
    }, {
        re: /&asymp;/gi,
        val: "≈"
    }, {
        re: /&ne;/gi,
        val: "≠"
    }, {
        re: /&le;/gi,
        val: "≤"
    }, {
        re: /&ge;/gi,
        val: "≥"
    }, {
        re: /&sub;/gi,
        val: "⊂"
    }, {
        re: /&sup;/gi,
        val: "⊃"
    }, {
        re: /&nsub;/gi,
        val: "⊄"
    }, {
        re: /&sube;/gi,
        val: "⊆"
    }, {
        re: /&supe;/gi,
        val: "⊇"
    }, {
        re: /&oplus;/gi,
        val: "⊕"
    }, {
        re: /&otimes;/gi,
        val: "⊗"
    }, {
        re: /&perp;/gi,
        val: "⊥"
    }, {
        re: /&sdot;/gi,
        val: "⋅"
    }, {
        re: /&Alpha;/gi,
        val: "Α"
    }, {
        re: /&Beta;/gi,
        val: "Β"
    }, {
        re: /&Gamma;/gi,
        val: "Γ"
    }, {
        re: /&Delta;/gi,
        val: "Δ"
    }, {
        re: /&Epsilon;/gi,
        val: "Ε"
    }, {
        re: /&Zeta;/gi,
        val: "Ζ"
    }, {
        re: /&Eta;/gi,
        val: "Η"
    }, {
        re: /&Theta;/gi,
        val: "Θ"
    }, {
        re: /&Iota;/gi,
        val: "Ι"
    }, {
        re: /&Kappa;/gi,
        val: "Κ"
    }, {
        re: /&Lambda;/gi,
        val: "Λ"
    }, {
        re: /&Mu;/gi,
        val: "Μ"
    }, {
        re: /&Nu;/gi,
        val: "Ν"
    }, {
        re: /&Xi;/gi,
        val: "Ν"
    }, {
        re: /&Omicron;/gi,
        val: "Ο"
    }, {
        re: /&Pi;/gi,
        val: "Π"
    }, {
        re: /&Rho;/gi,
        val: "Ρ"
    }, {
        re: /&Sigma;/gi,
        val: "Σ"
    }, {
        re: /&Tau;/gi,
        val: "Τ"
    }, {
        re: /&Upsilon;/gi,
        val: "Υ"
    }, {
        re: /&Phi;/gi,
        val: "Φ"
    }, {
        re: /&Chi;/gi,
        val: "Χ"
    }, {
        re: /&Psi;/gi,
        val: "Ψ"
    }, {
        re: /&Omega;/gi,
        val: "Ω"
    }, {
        re: /&alpha;/gi,
        val: "α"
    }, {
        re: /&beta;/gi,
        val: "β"
    }, {
        re: /&gamma;/gi,
        val: "γ"
    }, {
        re: /&delta;/gi,
        val: "δ"
    }, {
        re: /&epsilon;/gi,
        val: "ε"
    }, {
        re: /&zeta;/gi,
        val: "ζ"
    }, {
        re: /&eta;/gi,
        val: "η"
    }, {
        re: /&theta;/gi,
        val: "θ"
    }, {
        re: /&iota;/gi,
        val: "ι"
    }, {
        re: /&kappa;/gi,
        val: "κ"
    }, {
        re: /&lambda;/gi,
        val: "λ"
    }, {
        re: /&mu;/gi,
        val: "μ"
    }, {
        re: /&nu;/gi,
        val: "ν"
    }, {
        re: /&xi;/gi,
        val: "ξ"
    }, {
        re: /&omicron;/gi,
        val: "ο"
    }, {
        re: /&pi;/gi,
        val: "π"
    }, {
        re: /&rho;/gi,
        val: "ρ"
    }, {
        re: /&sigmaf;/gi,
        val: "ς"
    }, {
        re: /&sigma;/gi,
        val: "σ"
    }, {
        re: /&tau;/gi,
        val: "τ"
    }, {
        re: /&upsilon;/gi,
        val: "υ"
    }, {
        re: /&phi;/gi,
        val: "φ"
    }, {
        re: /&chi;/gi,
        val: "χ"
    }, {
        re: /&psi;/gi,
        val: "ψ"
    }, {
        re: /&omega;/gi,
        val: "ω"
    }, {
        re: /&thetasym;/gi,
        val: "ϑ"
    }, {
        re: /&upsih;/gi,
        val: "ϒ"
    }, {
        re: /&piv;/gi,
        val: "ϖ"
    }, {
        re: /&middot;/gi,
        val: "·"
    }, {
        re: /&nbsp;/gi,
        val: " "
    }, {
        re: /&quot;/gi,
        val: "＂"
    }, {
        re: /&amp;/gi,
        val: "&"
    }, {
        re: /&lt;/gi,
        val: "＜"
    }, {
        re: /&gt;/gi,
        val: "＞"
    }, {
        re: /&#8226;/gi,
        val: "•"
    }, {
        re: /&OElig;/gi,
        val: "Œ"
    }, {
        re: /&oelig;/gi,
        val: "œ"
    }, {
        re: /&Scaron;/gi,
        val: "Š"
    }, {
        re: /&scaron;/gi,
        val: "š"
    }, {
        re: /&Yuml;/gi,
        val: "Ÿ"
    }, {
        re: /&fnof;/gi,
        val: "ƒ"
    }, {
        re: /&circ;/gi,
        val: "ˆ"
    }, {
        re: /&tilde;/gi,
        val: "˜"
    }, {
        re: /&ensp;/gi,
        val: ""
    }, {
        re: /&emsp;/gi,
        val: ""
    }, {
        re: /&thinsp;/gi,
        val: ""
    }, {
        re: /&zwnj;/gi,
        val: ""
    }, {
        re: /&zwj;/gi,
        val: ""
    }, {
        re: /&lrm;/gi,
        val: ""
    }, {
        re: /&rlm;/gi,
        val: ""
    }, {
        re: /&ndash;/gi,
        val: "–"
    }, {
        re: /&mdash;/gi,
        val: "—"
    }, {
        re: /&lsquo;/gi,
        val: "‘"
    }, {
        re: /&rsquo;/gi,
        val: "’"
    }, {
        re: /&sbquo;/gi,
        val: "‚"
    }, {
        re: /&ldquo;/gi,
        val: "“"
    }, {
        re: /&rdquo;/gi,
        val: "”"
    }, {
        re: /&bdquo;/gi,
        val: "„"
    }, {
        re: /&dagger;/gi,
        val: "†"
    }, {
        re: /&Dagger;/gi,
        val: "‡"
    }, {
        re: /&bull;/gi,
        val: "•"
    }, {
        re: /&hellip;/gi,
        val: "…"
    }, {
        re: /&permil;/gi,
        val: "‰"
    }, {
        re: /&prime;/gi,
        val: "′"
    }, {
        re: /&Prime;/gi,
        val: "″"
    }, {
        re: /&lsaquo;/gi,
        val: "‹"
    }, {
        re: /&rsaquo;/gi,
        val: "›"
    }, {
        re: /&oline;/gi,
        val: "‾"
    }, {
        re: /&euro;/gi,
        val: "€"
    }, {
        re: /&trade;/gi,
        val: "™"
    }, {
        re: /&larr;/gi,
        val: "←"
    }, {
        re: /&uarr;/gi,
        val: "↑"
    }, {
        re: /&rarr;/gi,
        val: "→"
    }, {
        re: /&darr;/gi,
        val: "↓"
    }, {
        re: /&harr;/gi,
        val: "↔"
    }, {
        re: /&crarr;/gi,
        val: "↵"
    }, {
        re: /&lceil;/gi,
        val: "⌈"
    }, {
        re: /&rceil;/gi,
        val: "⌉"
    }, {
        re: /&lfloor;/gi,
        val: "⌊"
    }, {
        re: /&rfloor;/gi,
        val: "⌋"
    }, {
        re: /&loz;/gi,
        val: "◊"
    }, {
        re: /&spades;/gi,
        val: "♠"
    }, {
        re: /&clubs;/gi,
        val: "♣"
    }, {
        re: /&hearts;/gi,
        val: "♥"
    }, {
        re: /&diams;/gi,
        val: "♦"
    }, {
        re: /&#39;/gi,
        val: "＇"
    } ].forEach(function(r) {
        a = a.replace(r.re, r.val);
    }), a;
};